logging:
  level:
    ROOT: ERROR
    runsytem.vn.kotlin: ERROR
  file:
    path: log

server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.1.10.250:3306/kotlin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: runsystem
    password: Admin123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    mapping-resources:
      sql/user-sql.xml
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
jwt:
  secret: ZjE1OTcwZGRhOTg1ZTJlZjlmMDIwNTM5ZmI1NGI5NzYyZWNmNTExM2NhYzBmMmI0MzkwOTU1YjY2ZDRkZGIxYjM0MDIzZmJkMzNlMjE2N2UwMTIzYTJmYjlhYWFjYmNiNGIyOWFiYWQ1NjgwYmQzZTM5NTc3NTdmOTFlZDQ2M2M=
